apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-pv-volume-lopez
  namespace: msp
  labels:
    type: local
    patch-id: storage
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/msp/mqtt/lopez"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-pv-claim
  namespace: msp
  labels:
    patch-id: storage
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
