apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: msp
  labels:
    app: redis
  # namespace: envds-cloudy
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis-stack-server:6.2.6-v18
        # command:
        #   - redis-server
        #   - "/etc/redis-stack.conf"
        env:
        - name: REDIS_ARGS
          value: "--appendonly yes"
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 6379
          protocol: TCP
        volumeMounts:
          - name: redis-pv-storage
            mountPath: /data
          # - name: redis-config
          #   mountPath: /redis-stack.conf
            # subPath: redis-stack.conf
      volumes:
        - name: redis-pv-storage
          persistentVolumeClaim:
            claimName: redis-pv-claim
