apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: msp
  labels:
    app: redis
  # namespace: envds-cloudy
spec:
  selector:
    app: redis
  ports:
  - name: http
    protocol: TCP
    port: 6379
    targetPort: 6379
