apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datastore
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: msp
  source:
    repoURL: https://github.com/derekcoffman/test-gitops.git
    targetRevision: HEAD
    path: kustomize/apps/datastore/overlays/mspbase02
  #   path: 'argocd/lopez/mqtt.yaml'
  #   repoURL: 'https://github.com/derekcoffman/test-gitops.git'
  #   targetRevision: HEAD
  # sources:
  #   # - repoURL: https://github.com/derekcoffman/test-gitops.git
  #   #   targetRevision: HEAD
  #   #   path: kustomize/apps/nginx/overlays/dev
  #   - repoURL: https://github.com/derekcoffman/test-gitops.git
  #     targetRevision: HEAD
  #     path: kustomize/apps/mqtt/overlays/lopez
    # - repoURL: https://github.com/derekcoffman/test-gitops.git
    #   targetRevision: HEAD
    #   path: kustomize/apps/redis/overlays/lopez
  destination:
    server: https://kubernetes.default.svc
    namespace: msp-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  # syncOptions:
  #   - CreateNamespace=true
