apiVersion: v1
kind: Service
metadata:
  name: datastore
  namespace: msp-system
  labels:
    app: datastore
spec:
  selector:
    app: datastore
  ports:
  - name: http
    protocol: TCP
    # port: 8000
    port: 80
    # targetPort: 8000
    targetPort: 8080
  type: ClusterIP  