apiVersion: apps/v1
kind: Deployment
metadata:
  name: envds-relay
  namespace: msp
  labels:
    app: envds-relay
spec:
  selector:
    matchLabels:
      app: envds-relay
  template:
    metadata:
      labels:
        app: envds-relay
    spec:
      containers:
      - name: envds-relay
        image: ghcr.io/derekcoffman/envds-relay:v0.2.2
        imagePullPolicy: "Always"
        env:
          - name: ENVDS_ENV_ID
            value: default 
          # - name: REDIS_OM_URL
          #   value: redis://redis.default
          - name: LOG_LEVEL
            value: DEBUG
          # - name: ENVDS_RELAY_mqtt-auth-uasbase1-username
          #   valueFrom:
          #     secretKeyRef:
          #       name: mqtt-auth-uasbase1
          #       key: username
          # - name: ENVDS_RELAY_mqtt-auth-uasbase1-password
          #   valueFrom:
          #     secretKeyRef:
          #       name: mqtt-auth-uasbase1
          #       key: password
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 9080
          protocol: TCP
        volumeMounts:
          - name: envds-relay-config
            mountPath: /app/config/relay.conf
            subPath: relay.conf
      volumes:
        - name: envds-relay-config
          configMap:
            name: envds-relay-config
