apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: msp
  labels:
    app: mqtt
  # namespace: envds-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
      - name: mosquitto
        # image: localhost:5000/envds/eclipse-mosquitto:2.0.14
        # image: envds-registry:36301/eclipse-mosquitto:2.0.14
        # image: envds-registry:5000/core/eclipse-mosquitto:2.0.14
        # image: envds-registry:5000/core/eclipse-mosquitto:2.0.15
        image: eclipse-mosquitto:latest
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 1883
          protocol: TCP
        # - name: https
        #   containerPort: 8883
        #   protocol: TCP
        volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            - name: mosquitto-pv-storage
              mountPath: /mosquitto/data
            # - name: mosquitto-certs
            #   mountPath: /certs/ca.crt
            #   subPath: ca.crt
            # - name: mosquitto-certs
            #   mountPath: /certs/server.crt
            #   subPath: server.crt
            # - name: mosquitto-certs
            #   mountPath: /certs/server.key
            #   subPath: server.key
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
        - name: mosquitto-pv-storage
          persistentVolumeClaim:
            claimName: mosquitto-pv-claim
        # - name: mosquitto-certs
        #   configMap:
        #     name: mosquitto-certs
