apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: mqtt

# Example configuration for the webserver
# at https://github.com/monopole/hello
# commonLabels:
#   app: nginx

resources:
# - mqtt-ns.yaml
- mqtt-configmap.yaml
- mqtt-storage.yaml
- mqtt-deployment.yaml
- mqtt-service.yaml