apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: msp
  labels:
    app: mosquitto
  # namespace: envds-base
spec:
  selector:
    app: mosquitto
  ports:
  - name: http
    protocol: TCP
    port: 1883
    targetPort: 1883
  # - name: https
  #   port: 8883
  #   targetPort: 8883
  type: LoadBalancer
  # type: ClusterIP