apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nginx

# Example configuration for the webserver
# at https://github.com/monopole/hello
# namePrefix: dev-
# commonLabels:
#   app: nginx
#   variant: lopez

resources:
- ../../base
- nginx-sealedsecret.yaml

# patchesStrategicMerge:
#   - deployment.yaml